#!/bin/bash
if [ $# -eq 0 ];then
      echo 'Usage:/root/batchusers'
      exit 1
elif [ -f $1 ];then
	for i in $(cat $1)
	do
	useradd -s /bin/false $i 2>/dev/null
	if [ $? -ne 0 ];then
      	  echo 用户$i已存在
	else
      	  echo 用户$i创建成功
	fi
	done
else
      echo 'Input file not found'
      exit 2
fi
